# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proof.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproof.proto\"#\n\x05Token\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\r\"\x8b\x01\n\x03\x42ox\x12\x0e\n\x06output\x18\x01 \x01(\r\x12\x14\n\x0csigma_script\x18\x02 \x01(\x0c\x12\x16\n\x06tokens\x18\x03 \x03(\x0b\x32\x06.Token\x12\n\n\x02r4\x18\x04 \x01(\x0c\x12\n\n\x02r5\x18\x05 \x01(\x0c\x12\n\n\x02r6\x18\x06 \x01(\x0c\x12\n\n\x02r7\x18\x07 \x01(\x0c\x12\n\n\x02r8\x18\x08 \x01(\x0c\x12\n\n\x02r9\x18\t \x01(\x0c\"\x1f\n\x08\x42oxgroup\x12\x13\n\x05\x62oxes\x18\x01 \x03(\x0b\x32\x04.Boxb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proof_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOKEN']._serialized_start=15
  _globals['_TOKEN']._serialized_end=50
  _globals['_BOX']._serialized_start=53
  _globals['_BOX']._serialized_end=192
  _globals['_BOXGROUP']._serialized_start=194
  _globals['_BOXGROUP']._serialized_end=225
# @@protoc_insertion_point(module_scope)
